In [1]:
from pathlib import Path
import numpy as np

In [2]:
project_path = Path.cwd().parent
data_path = project_path / 'data' / 'SpO2'

input_path = data_path / 'SpO2_input_cleaned4%.csv'
output_path = data_path / 'SpO2_output_cleaned4%.csv'

assert input_path.exists(), "file does not exist"
assert output_path.exists(), "file does not exist"

weight_bit_width = 2
input_bit_width = 5  # originally, SpO2 data are 5 bits ([0-31])
weight_path = project_path/f"weights/SpO2/qat/quant_fc_{input_bit_width}bits_data_{weight_bit_width}bits_weights.csv"
assert weight_path.exists()

In [3]:
x = np.loadtxt(input_path, dtype=int, delimiter=',')
y = np.loadtxt(output_path, dtype=int, delimiter=',')
weights = np.loadtxt(weight_path, dtype=int, delimiter=',')

In [4]:
vi = x[1]

In [5]:
vi

array([26, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26,
       26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 26, 26, 26, 26, 26, 26,
       26, 26, 26, 26, 26, 26, 26, 25, 25, 25, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26,
       26, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 26, 26, 25, 24, 24,
       24, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 25, 25,
       25, 25, 25, 25, 25, 24, 24, 24, 24, 24, 24, 24, 23, 23, 23, 22, 22,
       21, 22, 22, 22, 22, 22, 23, 23, 24, 24, 24, 25, 25, 25, 25, 25, 25,
       25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25,
       25, 25, 25, 25, 25

In [6]:
weights.shape
weights

array([ 1,  1,  1,  0,  0,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0, -1,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0, -1,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  1,  0,  0, -1,  1,  1,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0, -1,
        0,  0,  0,  0,  0

In [7]:
vi.shape

(300,)

In [10]:
vi * weights

array([ 26,  25,  25,   0,   0,  25,  25,  25,  25,  25,   0,  25,  25,
        26,  26,  26,   0,  26,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0, -26,   0,   0, -26,   0,   0,   0,   0,   0,
         0,   0, -25,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0, -25,   0,   0,   0,
       -25,   0, -26,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,  22,   0,   0, -24,  24,  24,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [8]:
np.matmul(vi, weights)

-29

In [14]:
res = 0
for i, v in enumerate(vi):
    res += (weights[i] * v) % 65537
res % 65537

13209983

In [17]:
-25 % 65537

65512